#!/usr/bin/env bash
# config.template.sh — User configuration template for job-application-helper
#
# DO NOT edit this file directly.
#
# Option A (recommended): Run the onboarding script and it will generate
#   config.sh for you automatically:
#     python scripts/onboard.py --resume /path/to/your_resume.docx
#
# Option B (manual): Copy this file to config.sh and fill in the values:
#     cp config.template.sh config.sh
#     # then edit config.sh with your details
#
# config.sh is gitignored (your name/filenames stay private in your fork).
# config.template.sh is committed so you can always recreate config.sh.

# ---------------------------------------------------------------------------
# User identity
# ---------------------------------------------------------------------------
USER_FIRST_NAME="YourFirstName"
USER_LAST_NAME="YourLastName"

# ---------------------------------------------------------------------------
# Asset file basenames (files must exist in assets/)
# ---------------------------------------------------------------------------
# Resume .docx file — onboard.py copies your resume here automatically
RESUME_BASENAME="${USER_FIRST_NAME}_${USER_LAST_NAME}-RESUME.docx"

# Cover letter .docx template — optional; leave blank if not using one
COVERLETTER_BASENAME="${USER_FIRST_NAME}_${USER_LAST_NAME}-COVERLETTER.docx"

# ---------------------------------------------------------------------------
# Page count target
# ---------------------------------------------------------------------------
# Number of pages the tailored resume should be.
# onboard.py sets this to match your baseline resume's page count automatically.
TARGET_PAGES=2

# ---------------------------------------------------------------------------
# Output directory
# ---------------------------------------------------------------------------
# Where finished resumes, cover letters, and job description files are saved.
# Set to a folder outside the skill install so outputs stay separate from tooling.
# Leave empty to use assets/outputs/ within the skill directory (the default).
#
# Examples:
#   OUTPUT_DIR="$HOME/Documents/JobApplications"
#   OUTPUT_DIR="/c/Users/YourName/OneDrive/Documents/JobApplications"
OUTPUT_DIR=""
